name: CI/CD
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/—Åheckout@v3

      - name: Set up JDK 17
        uses: actions/checkout@v3

        with:
          distribution: 'temurin'
          java-version: '17'


      - name: Build with Gradle
        run:
          chmod +x ./gradlew
          ./gradlew clean build

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/for-sb-aws:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/for-sb-aws:latest
          

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Install SSH clients
        run: sudo apt-get install -y openssh-client

      - name: Add SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{secrets.AWS_SSH_KEY}}
          known_hosts: ${{secrets.EC2_KNOWN_HOST}}


      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_KNOWN_HOST }} "
          sudo docker pull ${{secrets.DOCKER_USERNAME}}/for-sb-aws:latest &&
          sudo docker stop my-sb-app || true &&
          sudo docker rm my-sb-app || true && 
          sudo docker run -d --name my-sb-app -p 8080:8080 ${{secrets.DOCKER_USERNAME}}/for-sb-aws:latest"